apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: second-project-devops
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: second-project-devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: second-project-devops
                port:
                  number: 80