apiVersion: v1
kind: Service
metadata:
  name: second-project-devops
  namespace: devops
  labels:
    app: second-project-devops
spec:
  type: ClusterIP
  selector:
    app: second-project-devops
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http